import { NextRequest, NextResponse } from 'next/server';
import { Resend } from 'resend';
import { rateLimit, getClientIp } from '@/lib/rateLimit';

const EMAIL_HOURLY_LIMIT = 5;
const EMAIL_DAILY_LIMIT = 20;
const ONE_HOUR = 60 * 60 * 1000;
const ONE_DAY = 24 * ONE_HOUR;

const CURRENCY_SYMBOLS: Record<string, string> = {
  USD: '$', EUR: '€', GBP: '£', CAD: '$', AUD: '$', JPY: '¥', INR: '₹',
};

export async function POST(request: NextRequest) {
  try {
    const ip = getClientIp(request);

    const hourly = rateLimit('email:hourly', ip, EMAIL_HOURLY_LIMIT, ONE_HOUR);
    if (!hourly.allowed) {
      return NextResponse.json(
        { error: `Too many requests. Please wait ${hourly.retryAfter} seconds before sending again.` },
        { status: 429, headers: { 'Retry-After': String(hourly.retryAfter) } }
      );
    }

    const daily = rateLimit('email:daily', ip, EMAIL_DAILY_LIMIT, ONE_DAY);
    if (!daily.allowed) {
      return NextResponse.json(
        { error: 'Daily email limit reached. Please try again tomorrow.' },
        { status: 429, headers: { 'Retry-After': String(daily.retryAfter) } }
      );
    }

    if (!process.env.RESEND_API_KEY) {
      console.error('[send-quote] RESEND_API_KEY environment variable is not set.');
      return NextResponse.json(
        { error: 'Email service is not configured. Please contact support.' },
        { status: 500 }
      );
    }

    const body = await request.json();
    const { clientName, clientEmail, companyName, totalPrice, currency, proposalText, quoteRef, today } = body;

    if (!clientName || !clientEmail || !companyName || !proposalText) {
      return NextResponse.json({ error: 'Missing required fields.' }, { status: 400 });
    }

    const symbol = CURRENCY_SYMBOLS[currency] ?? '$';
    const paragraphs = (proposalText as string).split(/\n\n+/).map((p: string) => p.trim()).filter(Boolean);

    const htmlBody = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Proposal from ${companyName}</title>
</head>
<body style="margin:0;padding:0;background-color:#f0f6ff;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:32px 16px;">

    <!-- Header -->
    <div style="background:linear-gradient(135deg,#1e3a8a,#2563eb);border-radius:16px 16px 0 0;padding:28px 32px;">
      <p style="font-size:10px;font-weight:700;color:rgba(255,255,255,0.55);text-transform:uppercase;letter-spacing:0.12em;margin:0 0 8px 0;">BUSINESS PROPOSAL</p>
      <p style="font-size:26px;font-weight:900;color:#ffffff;letter-spacing:-0.5px;margin:0 0 6px 0;">${companyName}</p>
      <p style="font-size:13px;color:rgba(255,255,255,0.65);margin:0;">Prepared for ${clientName} &nbsp;·&nbsp; ${today}</p>
    </div>

    <!-- Body -->
    <div style="background:#ffffff;padding:28px 32px;border-left:1px solid #dbeafe;border-right:1px solid #dbeafe;">
      ${paragraphs[0] ? `<p style="font-size:14px;color:#374151;line-height:1.8;margin:0 0 16px 0;">${paragraphs[0]}</p>` : ''}
      ${paragraphs[1] ? `<p style="font-size:14px;color:#374151;line-height:1.8;margin:0 0 16px 0;">${paragraphs[1]}</p>` : ''}

      <!-- Price highlight -->
      <div style="background:#f0f7ff;border:1px solid #bfdbfe;border-radius:12px;padding:18px 22px;margin:22px 0;">
        <p style="font-size:10px;font-weight:700;color:#2563eb;text-transform:uppercase;letter-spacing:0.12em;margin:0 0 6px 0;">TOTAL INVESTMENT</p>
        <p style="font-size:38px;font-weight:900;color:#111827;letter-spacing:-1.5px;margin:0;line-height:1;">${symbol}${totalPrice}</p>
        <p style="font-size:11px;color:#94a3b8;margin:6px 0 0 0;">All-inclusive · Payment terms to be discussed</p>
      </div>

      ${paragraphs.slice(2).map((p: string) => `<p style="font-size:13px;color:#4b5563;line-height:1.75;margin:0 0 12px 0;">${p}</p>`).join('')}

      <div style="border-top:1px solid #f1f5f9;margin-top:20px;padding-top:16px;">
        <p style="font-size:11px;color:#94a3b8;margin:0;">
          Quote Reference: <strong>${quoteRef}</strong> &nbsp;·&nbsp; Valid for 30 days from ${today}
        </p>
      </div>
    </div>

    <!-- Footer -->
    <div style="background:#1e3a8a;border-radius:0 0 16px 16px;padding:16px 32px;text-align:center;">
      <p style="font-size:11px;color:rgba(255,255,255,0.45);margin:0;">
        Generated by <strong style="color:rgba(255,255,255,0.65);">VoiceQuote AI</strong> &nbsp;·&nbsp; voicequoteai.vercel.app
      </p>
    </div>

  </div>
</body>
</html>`;

    const resend = new Resend(process.env.RESEND_API_KEY);

    const fromAddress = process.env.RESEND_FROM_EMAIL ?? 'proposals@voicequoteai.com';
    const replyTo = process.env.RESEND_REPLY_TO;

    const sendOptions: Parameters<typeof resend.emails.send>[0] = {
      from: fromAddress,
      to: clientEmail as string,
      subject: `Proposal from ${companyName} — ${symbol}${totalPrice}`,
      html: htmlBody,
    };
    if (replyTo) sendOptions.replyTo = replyTo;

    const { error } = await resend.emails.send(sendOptions);

    if (error) {
      console.error('[send-quote] Resend error:', error);
      return NextResponse.json({ error: 'Failed to send email. Please try again.' }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch (err) {
    console.error('[send-quote] Error:', err);
    return NextResponse.json({ error: 'Failed to send email. Please try again.' }, { status: 500 });
  }
}
